make: lib/Debug.class lib/ErrorHandler.class scanner/Scanner.class parser/CC4Parser.class ast/Ast.class semantic/Semantic.class irt/Irt.class opt/Algebraic.class opt/ConstantFolding.class codegen/Codegen.class Compiler.class

Compiler.class: Compiler.java
	javac Compiler.java

lib/Debug.class: lib/Debug.java
	javac lib/Debug.java

lib/ErrorHandler.class: lib/ErrorHandler.java
	javac lib/ErrorHandler.java

scanner/Scanner.class: scanner/Scanner.java
	javac scanner/Scanner.java

parser/CC4Parser.class: parser/CC4Parser.java
	javac parser/CC4Parser.java

ast/Ast.class: ast/Ast.java
	javac ast/Ast.java

semantic/Semantic.class: semantic/Semantic.java
	javac semantic/Semantic.java

irt/Irt.class: irt/Irt.java
	javac irt/Irt.java

opt/Algebraic.class: opt/Algebraic.java
	javac opt/Algebraic.java

opt/ConstantFolding.class: opt/ConstantFolding.java
	javac opt/ConstantFolding.java

codegen/Codegen.class: codegen/Codegen.java
	javac codegen/Codegen.java

clean:
	rm -f Compiler.class
	rm -f scanner/Scanner.class
	rm -f parser/CC4Parser.class
	rm -f ast/Ast.class
	rm -f semantic/Semantic.class
	rm -f irt/Irt.class
	rm -f opt/Algebraic.class
	rm -f opt/ConstantFolding.class
	rm -f codegen/Codegen.class
	rm -f lib/Debug.class